/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ConfigDB();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigDB', function() {
    it('should create an instance of ConfigDB', function() {
      // uncomment below and update the code to test ConfigDB
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be.a(PiianoVaultRestApi.ConfigDB);
    });

    it('should have the property connMaxLifetimeMinutes (base name: "conn_max_lifetime_minutes")', function() {
      // uncomment below and update the code to test the property connMaxLifetimeMinutes
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property gc (base name: "gc")', function() {
      // uncomment below and update the code to test the property gc
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property hostname (base name: "hostname")', function() {
      // uncomment below and update the code to test the property hostname
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property maxIdleConns (base name: "max_idle_conns")', function() {
      // uncomment below and update the code to test the property maxIdleConns
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property maxOpenConns (base name: "max_open_conns")', function() {
      // uncomment below and update the code to test the property maxOpenConns
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property migration (base name: "migration")', function() {
      // uncomment below and update the code to test the property migration
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property port (base name: "port")', function() {
      // uncomment below and update the code to test the property port
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property requireTls (base name: "require_tls")', function() {
      // uncomment below and update the code to test the property requireTls
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instance = new PiianoVaultRestApi.ConfigDB();
      //expect(instance).to.be();
    });

  });

}));
