/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ConfigTLS();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigTLS', function() {
    it('should create an instance of ConfigTLS', function() {
      // uncomment below and update the code to test ConfigTLS
      //var instance = new PiianoVaultRestApi.ConfigTLS();
      //expect(instance).to.be.a(PiianoVaultRestApi.ConfigTLS);
    });

    it('should have the property certFile (base name: "cert_file")', function() {
      // uncomment below and update the code to test the property certFile
      //var instance = new PiianoVaultRestApi.ConfigTLS();
      //expect(instance).to.be();
    });

    it('should have the property enable (base name: "enable")', function() {
      // uncomment below and update the code to test the property enable
      //var instance = new PiianoVaultRestApi.ConfigTLS();
      //expect(instance).to.be();
    });

    it('should have the property keyFile (base name: "key_file")', function() {
      // uncomment below and update the code to test the property keyFile
      //var instance = new PiianoVaultRestApi.ConfigTLS();
      //expect(instance).to.be();
    });

    it('should have the property selfsigned (base name: "selfsigned")', function() {
      // uncomment below and update the code to test the property selfsigned
      //var instance = new PiianoVaultRestApi.ConfigTLS();
      //expect(instance).to.be();
    });

  });

}));
