/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ConfigConfig();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigConfig', function() {
    it('should create an instance of ConfigConfig', function() {
      // uncomment below and update the code to test ConfigConfig
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be.a(PiianoVaultRestApi.ConfigConfig);
    });

    it('should have the property db (base name: "db")', function() {
      // uncomment below and update the code to test the property db
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property devmode (base name: "devmode")', function() {
      // uncomment below and update the code to test the property devmode
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property kms (base name: "kms")', function() {
      // uncomment below and update the code to test the property kms
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property log (base name: "log")', function() {
      // uncomment below and update the code to test the property log
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property sentry (base name: "sentry")', function() {
      // uncomment below and update the code to test the property sentry
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property service (base name: "service")', function() {
      // uncomment below and update the code to test the property service
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property tls (base name: "tls")', function() {
      // uncomment below and update the code to test the property tls
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

    it('should have the property ttl (base name: "ttl")', function() {
      // uncomment below and update the code to test the property ttl
      //var instance = new PiianoVaultRestApi.ConfigConfig();
      //expect(instance).to.be();
    });

  });

}));
