/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ConfigLog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConfigLog', function() {
    it('should create an instance of ConfigLog', function() {
      // uncomment below and update the code to test ConfigLog
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be.a(PiianoVaultRestApi.ConfigLog);
    });

    it('should have the property customerEnv (base name: "customer_env")', function() {
      // uncomment below and update the code to test the property customerEnv
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be();
    });

    it('should have the property customerIdentifier (base name: "customer_identifier")', function() {
      // uncomment below and update the code to test the property customerIdentifier
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be();
    });

    it('should have the property datadogApmEnable (base name: "datadog_apm_enable")', function() {
      // uncomment below and update the code to test the property datadogApmEnable
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be();
    });

    it('should have the property datadogEnable (base name: "datadog_enable")', function() {
      // uncomment below and update the code to test the property datadogEnable
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be();
    });

    it('should have the property datadogSource (base name: "datadog_source")', function() {
      // uncomment below and update the code to test the property datadogSource
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be();
    });

    it('should have the property level (base name: "level")', function() {
      // uncomment below and update the code to test the property level
      //var instance = new PiianoVaultRestApi.ConfigLog();
      //expect(instance).to.be();
    });

  });

}));
