/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelsTokenizeRequest', function() {
    it('should create an instance of ModelsTokenizeRequest', function() {
      // uncomment below and update the code to test ModelsTokenizeRequest
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be.a(PiianoVaultRestApi.ModelsTokenizeRequest);
    });

    it('should have the property fpprops (base name: "fpprops")', function() {
      // uncomment below and update the code to test the property fpprops
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property fptemplate (base name: "fptemplate")', function() {
      // uncomment below and update the code to test the property fptemplate
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property objectIds (base name: "object_ids")', function() {
      // uncomment below and update the code to test the property objectIds
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property props (base name: "props")', function() {
      // uncomment below and update the code to test the property props
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property reuseTokenId (base name: "reuse_token_id")', function() {
      // uncomment below and update the code to test the property reuseTokenId
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property reversible (base name: "reversible")', function() {
      // uncomment below and update the code to test the property reversible
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new PiianoVaultRestApi.ModelsTokenizeRequest();
      //expect(instance).to.be();
    });

  });

}));
