/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ModelsProperty();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelsProperty', function() {
    it('should create an instance of ModelsProperty', function() {
      // uncomment below and update the code to test ModelsProperty
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be.a(PiianoVaultRestApi.ModelsProperty);
    });

    it('should have the property creationTime (base name: "creation_time")', function() {
      // uncomment below and update the code to test the property creationTime
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isArray (base name: "is_array")', function() {
      // uncomment below and update the code to test the property isArray
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isBuiltin (base name: "is_builtin")', function() {
      // uncomment below and update the code to test the property isBuiltin
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isEncrypted (base name: "is_encrypted")', function() {
      // uncomment below and update the code to test the property isEncrypted
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isIndex (base name: "is_index")', function() {
      // uncomment below and update the code to test the property isIndex
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isNullable (base name: "is_nullable")', function() {
      // uncomment below and update the code to test the property isNullable
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isReadonly (base name: "is_readonly")', function() {
      // uncomment below and update the code to test the property isReadonly
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property isUnique (base name: "is_unique")', function() {
      // uncomment below and update the code to test the property isUnique
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property modificationTime (base name: "modification_time")', function() {
      // uncomment below and update the code to test the property modificationTime
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

    it('should have the property piiTypeName (base name: "pii_type_name")', function() {
      // uncomment below and update the code to test the property piiTypeName
      //var instance = new PiianoVaultRestApi.ModelsProperty();
      //expect(instance).to.be();
    });

  });

}));
