/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ModelsWorker();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelsWorker', function() {
    it('should create an instance of ModelsWorker', function() {
      // uncomment below and update the code to test ModelsWorker
      //var instance = new PiianoVaultRestApi.ModelsWorker();
      //expect(instance).to.be.a(PiianoVaultRestApi.ModelsWorker);
    });

    it('should have the property workerId (base name: "worker_id")', function() {
      // uncomment below and update the code to test the property workerId
      //var instance = new PiianoVaultRestApi.ModelsWorker();
      //expect(instance).to.be();
    });

    it('should have the property generationNumber (base name: "generation_number")', function() {
      // uncomment below and update the code to test the property generationNumber
      //var instance = new PiianoVaultRestApi.ModelsWorker();
      //expect(instance).to.be();
    });

    it('should have the property modifiedAt (base name: "modified_at")', function() {
      // uncomment below and update the code to test the property modifiedAt
      //var instance = new PiianoVaultRestApi.ModelsWorker();
      //expect(instance).to.be();
    });

    it('should have the property refreshIntervalSeconds (base name: "refresh_interval_seconds")', function() {
      // uncomment below and update the code to test the property refreshIntervalSeconds
      //var instance = new PiianoVaultRestApi.ModelsWorker();
      //expect(instance).to.be();
    });

  });

}));
