/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModelsTokenRefMetadata', function() {
    it('should create an instance of ModelsTokenRefMetadata', function() {
      // uncomment below and update the code to test ModelsTokenRefMetadata
      //var instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
      //expect(instance).to.be.a(PiianoVaultRestApi.ModelsTokenRefMetadata);
    });

    it('should have the property creationTime (base name: "creation_time")', function() {
      // uncomment below and update the code to test the property creationTime
      //var instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
      //expect(instance).to.be();
    });

    it('should have the property effectiveExpirationTime (base name: "effective_expiration_time")', function() {
      // uncomment below and update the code to test the property effectiveExpirationTime
      //var instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
      //expect(instance).to.be();
    });

    it('should have the property expirationTime (base name: "expiration_time")', function() {
      // uncomment below and update the code to test the property expirationTime
      //var instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
      //expect(instance).to.be();
    });

    it('should have the property objectId (base name: "object_id")', function() {
      // uncomment below and update the code to test the property objectId
      //var instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new PiianoVaultRestApi.ModelsTokenRefMetadata();
      //expect(instance).to.be();
    });

  });

}));
