/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PiianoVaultRestApi);
  }
}(this, function(expect, PiianoVaultRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PiianoVaultRestApi.CollectionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CollectionsApi', function() {
    describe('addCollection', function() {
      it('should call addCollection successfully', function(done) {
        //uncomment below and update the code to test addCollection
        //instance.addCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addCollectionProperty', function() {
      it('should call addCollectionProperty successfully', function(done) {
        //uncomment below and update the code to test addCollectionProperty
        //instance.addCollectionProperty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCollection', function() {
      it('should call deleteCollection successfully', function(done) {
        //uncomment below and update the code to test deleteCollection
        //instance.deleteCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCollectionProperty', function() {
      it('should call deleteCollectionProperty successfully', function(done) {
        //uncomment below and update the code to test deleteCollectionProperty
        //instance.deleteCollectionProperty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllCollections', function() {
      it('should call getAllCollections successfully', function(done) {
        //uncomment below and update the code to test getAllCollections
        //instance.getAllCollections(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCollection', function() {
      it('should call getCollection successfully', function(done) {
        //uncomment below and update the code to test getCollection
        //instance.getCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCollectionProperty', function() {
      it('should call getCollectionProperty successfully', function(done) {
        //uncomment below and update the code to test getCollectionProperty
        //instance.getCollectionProperty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listCollectionProperties', function() {
      it('should call listCollectionProperties successfully', function(done) {
        //uncomment below and update the code to test listCollectionProperties
        //instance.listCollectionProperties(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCollection', function() {
      it('should call updateCollection successfully', function(done) {
        //uncomment below and update the code to test updateCollection
        //instance.updateCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCollectionProperty', function() {
      it('should call updateCollectionProperty successfully', function(done) {
        //uncomment below and update the code to test updateCollectionProperty
        //instance.updateCollectionProperty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
