/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthConfig from '../model/AuthConfig';
import ModelsUserName from '../model/ModelsUserName';
import RestHTTPError from '../model/RestHTTPError';

/**
* IAM service.
* @module api/IAMApi
* @version 1.0
*/
export default class IAMApi {

    /**
    * Constructs a new IAMApi. 
    * @alias module:api/IAMApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getIamConf operation.
     * @callback module:api/IAMApi~getIamConfCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AuthConfig} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get IAM configuration
     * @param {module:model/String} reason Details of the reason for requesting the property. The default is set when no access reason is provided and PVAULT_SERVICE_FORCE_ACCESS_REASON is false.
     * @param {Object} opts Optional parameters
     * @param {String} opts.adhocReason An ad-hoc reason for accessing the Vault data.
     * @param {module:api/IAMApi~getIamConfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AuthConfig}
     */
    getIamConf(reason, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'reason' is set
      if (reason === undefined || reason === null) {
        throw new Error("Missing the required parameter 'reason' when calling getIamConf");
      }

      let pathParams = {
      };
      let queryParams = {
        'adhoc_reason': opts['adhocReason'],
        'reason': reason
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/toml', 'application/json'];
      let returnType = AuthConfig;
      return this.apiClient.callApi(
        '/api/pvlt/1.0/ctl/iam/conf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the regenerateUserApiKey operation.
     * @callback module:api/IAMApi~regenerateUserApiKeyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Regenerate user API key
     * @param {module:model/String} reason Details of the reason for requesting the property. The default is set when no access reason is provided and PVAULT_SERVICE_FORCE_ACCESS_REASON is false.
     * @param {module:model/ModelsUserName} modelsUserName The name of the user to regenerate API key for.
     * @param {Object} opts Optional parameters
     * @param {String} opts.adhocReason An ad-hoc reason for accessing the Vault data.
     * @param {module:api/IAMApi~regenerateUserApiKeyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    regenerateUserApiKey(reason, modelsUserName, opts, callback) {
      opts = opts || {};
      let postBody = modelsUserName;
      // verify the required parameter 'reason' is set
      if (reason === undefined || reason === null) {
        throw new Error("Missing the required parameter 'reason' when calling regenerateUserApiKey");
      }
      // verify the required parameter 'modelsUserName' is set
      if (modelsUserName === undefined || modelsUserName === null) {
        throw new Error("Missing the required parameter 'modelsUserName' when calling regenerateUserApiKey");
      }

      let pathParams = {
      };
      let queryParams = {
        'adhoc_reason': opts['adhocReason'],
        'reason': reason
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/pvlt/1.0/ctl/iam/user/regen', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the setIamConf operation.
     * @callback module:api/IAMApi~setIamConfCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Set IAM configuration
     * @param {module:model/String} reason Details of the reason for requesting the property. The default is set when no access reason is provided and PVAULT_SERVICE_FORCE_ACCESS_REASON is false.
     * @param {module:model/AuthConfig} authConfig IAM configuration in TOML format.
     * @param {Object} opts Optional parameters
     * @param {String} opts.adhocReason An ad-hoc reason for accessing the Vault data.
     * @param {module:api/IAMApi~setIamConfCallback} callback The callback function, accepting three arguments: error, data, response
     */
    setIamConf(reason, authConfig, opts, callback) {
      opts = opts || {};
      let postBody = authConfig;
      // verify the required parameter 'reason' is set
      if (reason === undefined || reason === null) {
        throw new Error("Missing the required parameter 'reason' when calling setIamConf");
      }
      // verify the required parameter 'authConfig' is set
      if (authConfig === undefined || authConfig === null) {
        throw new Error("Missing the required parameter 'authConfig' when calling setIamConf");
      }

      let pathParams = {
      };
      let queryParams = {
        'adhoc_reason': opts['adhocReason'],
        'reason': reason
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/toml'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/pvlt/1.0/ctl/iam/conf', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
