/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthRole model module.
 * @module model/AuthRole
 * @version 1.0
 */
class AuthRole {
    /**
     * Constructs a new <code>AuthRole</code>.
     * @alias module:model/AuthRole
     */
    constructor() { 
        
        AuthRole.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthRole</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthRole} obj Optional instance to populate.
     * @return {module:model/AuthRole} The populated <code>AuthRole</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthRole();

            if (data.hasOwnProperty('capabilities')) {
                obj['capabilities'] = ApiClient.convertToType(data['capabilities'], ['String']);
            }
            if (data.hasOwnProperty('policies')) {
                obj['policies'] = ApiClient.convertToType(data['policies'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} capabilities
 */
AuthRole.prototype['capabilities'] = undefined;

/**
 * @member {Array.<String>} policies
 */
AuthRole.prototype['policies'] = undefined;






export default AuthRole;

