/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthPolicy model module.
 * @module model/AuthPolicy
 * @version 1.0
 */
class AuthPolicy {
    /**
     * Constructs a new <code>AuthPolicy</code>.
     * @alias module:model/AuthPolicy
     */
    constructor() { 
        
        AuthPolicy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthPolicy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthPolicy} obj Optional instance to populate.
     * @return {module:model/AuthPolicy} The populated <code>AuthPolicy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthPolicy();

            if (data.hasOwnProperty('operations')) {
                obj['operations'] = ApiClient.convertToType(data['operations'], ['String']);
            }
            if (data.hasOwnProperty('policyType')) {
                obj['policyType'] = ApiClient.convertToType(data['policyType'], 'String');
            }
            if (data.hasOwnProperty('reasons')) {
                obj['reasons'] = ApiClient.convertToType(data['reasons'], ['String']);
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = ApiClient.convertToType(data['resources'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} operations
 */
AuthPolicy.prototype['operations'] = undefined;

/**
 * @member {String} policyType
 */
AuthPolicy.prototype['policyType'] = undefined;

/**
 * @member {Array.<String>} reasons
 */
AuthPolicy.prototype['reasons'] = undefined;

/**
 * @member {Array.<String>} resources
 */
AuthPolicy.prototype['resources'] = undefined;






export default AuthPolicy;

