/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigTLS model module.
 * @module model/ConfigTLS
 * @version 1.0
 */
class ConfigTLS {
    /**
     * Constructs a new <code>ConfigTLS</code>.
     * @alias module:model/ConfigTLS
     */
    constructor() { 
        
        ConfigTLS.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigTLS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigTLS} obj Optional instance to populate.
     * @return {module:model/ConfigTLS} The populated <code>ConfigTLS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigTLS();

            if (data.hasOwnProperty('cert_file')) {
                obj['cert_file'] = ApiClient.convertToType(data['cert_file'], 'String');
            }
            if (data.hasOwnProperty('enable')) {
                obj['enable'] = ApiClient.convertToType(data['enable'], 'Boolean');
            }
            if (data.hasOwnProperty('key_file')) {
                obj['key_file'] = ApiClient.convertToType(data['key_file'], 'String');
            }
            if (data.hasOwnProperty('selfsigned')) {
                obj['selfsigned'] = ApiClient.convertToType(data['selfsigned'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cert_file
 */
ConfigTLS.prototype['cert_file'] = undefined;

/**
 * @member {Boolean} enable
 */
ConfigTLS.prototype['enable'] = undefined;

/**
 * @member {String} key_file
 */
ConfigTLS.prototype['key_file'] = undefined;

/**
 * @member {Boolean} selfsigned
 */
ConfigTLS.prototype['selfsigned'] = undefined;






export default ConfigTLS;

