/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigMigration model module.
 * @module model/ConfigMigration
 * @version 1.0
 */
class ConfigMigration {
    /**
     * Constructs a new <code>ConfigMigration</code>.
     * @alias module:model/ConfigMigration
     */
    constructor() { 
        
        ConfigMigration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigMigration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigMigration} obj Optional instance to populate.
     * @return {module:model/ConfigMigration} The populated <code>ConfigMigration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigMigration();

            if (data.hasOwnProperty('auto_run')) {
                obj['auto_run'] = ApiClient.convertToType(data['auto_run'], 'Boolean');
            }
            if (data.hasOwnProperty('enable_retries')) {
                obj['enable_retries'] = ApiClient.convertToType(data['enable_retries'], 'Boolean');
            }
            if (data.hasOwnProperty('initial_wait_between_retries')) {
                obj['initial_wait_between_retries'] = ApiClient.convertToType(data['initial_wait_between_retries'], 'Number');
            }
            if (data.hasOwnProperty('max_retries')) {
                obj['max_retries'] = ApiClient.convertToType(data['max_retries'], 'Number');
            }
            if (data.hasOwnProperty('max_wait_between_retries')) {
                obj['max_wait_between_retries'] = ApiClient.convertToType(data['max_wait_between_retries'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} auto_run
 */
ConfigMigration.prototype['auto_run'] = undefined;

/**
 * @member {Boolean} enable_retries
 */
ConfigMigration.prototype['enable_retries'] = undefined;

/**
 * @member {Number} initial_wait_between_retries
 */
ConfigMigration.prototype['initial_wait_between_retries'] = undefined;

/**
 * @member {Number} max_retries
 */
ConfigMigration.prototype['max_retries'] = undefined;

/**
 * @member {Number} max_wait_between_retries
 */
ConfigMigration.prototype['max_wait_between_retries'] = undefined;






export default ConfigMigration;

