/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigLog model module.
 * @module model/ConfigLog
 * @version 1.0
 */
class ConfigLog {
    /**
     * Constructs a new <code>ConfigLog</code>.
     * @alias module:model/ConfigLog
     */
    constructor() { 
        
        ConfigLog.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigLog} obj Optional instance to populate.
     * @return {module:model/ConfigLog} The populated <code>ConfigLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigLog();

            if (data.hasOwnProperty('customer_env')) {
                obj['customer_env'] = ApiClient.convertToType(data['customer_env'], 'String');
            }
            if (data.hasOwnProperty('customer_identifier')) {
                obj['customer_identifier'] = ApiClient.convertToType(data['customer_identifier'], 'String');
            }
            if (data.hasOwnProperty('datadog_apm_enable')) {
                obj['datadog_apm_enable'] = ApiClient.convertToType(data['datadog_apm_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('datadog_enable')) {
                obj['datadog_enable'] = ApiClient.convertToType(data['datadog_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('datadog_source')) {
                obj['datadog_source'] = ApiClient.convertToType(data['datadog_source'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} customer_env
 */
ConfigLog.prototype['customer_env'] = undefined;

/**
 * @member {String} customer_identifier
 */
ConfigLog.prototype['customer_identifier'] = undefined;

/**
 * @member {Boolean} datadog_apm_enable
 */
ConfigLog.prototype['datadog_apm_enable'] = undefined;

/**
 * @member {Boolean} datadog_enable
 */
ConfigLog.prototype['datadog_enable'] = undefined;

/**
 * @member {String} datadog_source
 */
ConfigLog.prototype['datadog_source'] = undefined;

/**
 * @member {String} level
 */
ConfigLog.prototype['level'] = undefined;






export default ConfigLog;

