/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConfigGC from './ConfigGC';
import ConfigMigration from './ConfigMigration';

/**
 * The ConfigDB model module.
 * @module model/ConfigDB
 * @version 1.0
 */
class ConfigDB {
    /**
     * Constructs a new <code>ConfigDB</code>.
     * @alias module:model/ConfigDB
     */
    constructor() { 
        
        ConfigDB.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigDB</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigDB} obj Optional instance to populate.
     * @return {module:model/ConfigDB} The populated <code>ConfigDB</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigDB();

            if (data.hasOwnProperty('conn_max_lifetime_minutes')) {
                obj['conn_max_lifetime_minutes'] = ApiClient.convertToType(data['conn_max_lifetime_minutes'], 'Number');
            }
            if (data.hasOwnProperty('gc')) {
                obj['gc'] = ConfigGC.constructFromObject(data['gc']);
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('max_idle_conns')) {
                obj['max_idle_conns'] = ApiClient.convertToType(data['max_idle_conns'], 'Number');
            }
            if (data.hasOwnProperty('max_open_conns')) {
                obj['max_open_conns'] = ApiClient.convertToType(data['max_open_conns'], 'Number');
            }
            if (data.hasOwnProperty('migration')) {
                obj['migration'] = ConfigMigration.constructFromObject(data['migration']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('require_tls')) {
                obj['require_tls'] = ApiClient.convertToType(data['require_tls'], 'Boolean');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} conn_max_lifetime_minutes
 */
ConfigDB.prototype['conn_max_lifetime_minutes'] = undefined;

/**
 * @member {module:model/ConfigGC} gc
 */
ConfigDB.prototype['gc'] = undefined;

/**
 * @member {String} hostname
 */
ConfigDB.prototype['hostname'] = undefined;

/**
 * @member {Number} max_idle_conns
 */
ConfigDB.prototype['max_idle_conns'] = undefined;

/**
 * @member {Number} max_open_conns
 */
ConfigDB.prototype['max_open_conns'] = undefined;

/**
 * @member {module:model/ConfigMigration} migration
 */
ConfigDB.prototype['migration'] = undefined;

/**
 * @member {String} name
 */
ConfigDB.prototype['name'] = undefined;

/**
 * @member {String} password
 */
ConfigDB.prototype['password'] = undefined;

/**
 * @member {Number} port
 */
ConfigDB.prototype['port'] = undefined;

/**
 * @member {Boolean} require_tls
 */
ConfigDB.prototype['require_tls'] = undefined;

/**
 * @member {String} user
 */
ConfigDB.prototype['user'] = undefined;






export default ConfigDB;

