/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigTTL model module.
 * @module model/ConfigTTL
 * @version 1.0
 */
class ConfigTTL {
    /**
     * Constructs a new <code>ConfigTTL</code>.
     * @alias module:model/ConfigTTL
     */
    constructor() { 
        
        ConfigTTL.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigTTL</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigTTL} obj Optional instance to populate.
     * @return {module:model/ConfigTTL} The populated <code>ConfigTTL</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigTTL();

            if (data.hasOwnProperty('associated_objects')) {
                obj['associated_objects'] = ApiClient.convertToType(data['associated_objects'], 'Number');
            }
            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], 'Number');
            }
            if (data.hasOwnProperty('unassociated_objects')) {
                obj['unassociated_objects'] = ApiClient.convertToType(data['unassociated_objects'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} associated_objects
 */
ConfigTTL.prototype['associated_objects'] = undefined;

/**
 * @member {Number} tokens
 */
ConfigTTL.prototype['tokens'] = undefined;

/**
 * @member {Number} unassociated_objects
 */
ConfigTTL.prototype['unassociated_objects'] = undefined;






export default ConfigTTL;

