/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigFeatures model module.
 * @module model/ConfigFeatures
 * @version 1.0
 */
class ConfigFeatures {
    /**
     * Constructs a new <code>ConfigFeatures</code>.
     * @alias module:model/ConfigFeatures
     */
    constructor() { 
        
        ConfigFeatures.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigFeatures} obj Optional instance to populate.
     * @return {module:model/ConfigFeatures} The populated <code>ConfigFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigFeatures();

            if (data.hasOwnProperty('api_key_hashing')) {
                obj['api_key_hashing'] = ApiClient.convertToType(data['api_key_hashing'], 'Boolean');
            }
            if (data.hasOwnProperty('encryption')) {
                obj['encryption'] = ApiClient.convertToType(data['encryption'], 'Boolean');
            }
            if (data.hasOwnProperty('policy_enforcement')) {
                obj['policy_enforcement'] = ApiClient.convertToType(data['policy_enforcement'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} api_key_hashing
 */
ConfigFeatures.prototype['api_key_hashing'] = undefined;

/**
 * @member {Boolean} encryption
 */
ConfigFeatures.prototype['encryption'] = undefined;

/**
 * @member {Boolean} policy_enforcement
 */
ConfigFeatures.prototype['policy_enforcement'] = undefined;






export default ConfigFeatures;

