/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigService model module.
 * @module model/ConfigService
 * @version 1.0
 */
class ConfigService {
    /**
     * Constructs a new <code>ConfigService</code>.
     * @alias module:model/ConfigService
     */
    constructor() { 
        
        ConfigService.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigService</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigService} obj Optional instance to populate.
     * @return {module:model/ConfigService} The populated <code>ConfigService</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigService();

            if (data.hasOwnProperty('admin_api_key')) {
                obj['admin_api_key'] = ApiClient.convertToType(data['admin_api_key'], 'String');
            }
            if (data.hasOwnProperty('admin_may_read_data')) {
                obj['admin_may_read_data'] = ApiClient.convertToType(data['admin_may_read_data'], 'Boolean');
            }
            if (data.hasOwnProperty('default_page_size')) {
                obj['default_page_size'] = ApiClient.convertToType(data['default_page_size'], 'Number');
            }
            if (data.hasOwnProperty('force_access_reason')) {
                obj['force_access_reason'] = ApiClient.convertToType(data['force_access_reason'], 'Boolean');
            }
            if (data.hasOwnProperty('listen_addr')) {
                obj['listen_addr'] = ApiClient.convertToType(data['listen_addr'], 'String');
            }
            if (data.hasOwnProperty('max_page_size')) {
                obj['max_page_size'] = ApiClient.convertToType(data['max_page_size'], 'Number');
            }
            if (data.hasOwnProperty('timeout_seconds')) {
                obj['timeout_seconds'] = ApiClient.convertToType(data['timeout_seconds'], 'Number');
            }
            if (data.hasOwnProperty('cache_refresh_interval_seconds')) {
                obj['cache_refresh_interval_seconds'] = ApiClient.convertToType(data['cache_refresh_interval_seconds'], 'Number');
            }
            if (data.hasOwnProperty('license')) {
                obj['license'] = ApiClient.convertToType(data['license'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} admin_api_key
 */
ConfigService.prototype['admin_api_key'] = undefined;

/**
 * @member {Boolean} admin_may_read_data
 */
ConfigService.prototype['admin_may_read_data'] = undefined;

/**
 * @member {Number} default_page_size
 */
ConfigService.prototype['default_page_size'] = undefined;

/**
 * @member {Boolean} force_access_reason
 */
ConfigService.prototype['force_access_reason'] = undefined;

/**
 * @member {String} listen_addr
 */
ConfigService.prototype['listen_addr'] = undefined;

/**
 * @member {Number} max_page_size
 */
ConfigService.prototype['max_page_size'] = undefined;

/**
 * @member {Number} timeout_seconds
 */
ConfigService.prototype['timeout_seconds'] = undefined;

/**
 * @member {Number} cache_refresh_interval_seconds
 */
ConfigService.prototype['cache_refresh_interval_seconds'] = undefined;

/**
 * @member {String} license
 */
ConfigService.prototype['license'] = undefined;






export default ConfigService;

