/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConfigDB from './ConfigDB';
import ConfigFeatures from './ConfigFeatures';
import ConfigKMS from './ConfigKMS';
import ConfigLog from './ConfigLog';
import ConfigSentry from './ConfigSentry';
import ConfigService from './ConfigService';
import ConfigTLS from './ConfigTLS';
import ConfigTTL from './ConfigTTL';

/**
 * The ConfigConfig model module.
 * @module model/ConfigConfig
 * @version 1.0
 */
class ConfigConfig {
    /**
     * Constructs a new <code>ConfigConfig</code>.
     * @alias module:model/ConfigConfig
     */
    constructor() { 
        
        ConfigConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigConfig} obj Optional instance to populate.
     * @return {module:model/ConfigConfig} The populated <code>ConfigConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigConfig();

            if (data.hasOwnProperty('db')) {
                obj['db'] = ConfigDB.constructFromObject(data['db']);
            }
            if (data.hasOwnProperty('devmode')) {
                obj['devmode'] = ApiClient.convertToType(data['devmode'], 'Boolean');
            }
            if (data.hasOwnProperty('features')) {
                obj['features'] = ConfigFeatures.constructFromObject(data['features']);
            }
            if (data.hasOwnProperty('kms')) {
                obj['kms'] = ConfigKMS.constructFromObject(data['kms']);
            }
            if (data.hasOwnProperty('log')) {
                obj['log'] = ConfigLog.constructFromObject(data['log']);
            }
            if (data.hasOwnProperty('sentry')) {
                obj['sentry'] = ConfigSentry.constructFromObject(data['sentry']);
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = ConfigService.constructFromObject(data['service']);
            }
            if (data.hasOwnProperty('tls')) {
                obj['tls'] = ConfigTLS.constructFromObject(data['tls']);
            }
            if (data.hasOwnProperty('ttl')) {
                obj['ttl'] = ConfigTTL.constructFromObject(data['ttl']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ConfigDB} db
 */
ConfigConfig.prototype['db'] = undefined;

/**
 * @member {Boolean} devmode
 */
ConfigConfig.prototype['devmode'] = undefined;

/**
 * @member {module:model/ConfigFeatures} features
 */
ConfigConfig.prototype['features'] = undefined;

/**
 * @member {module:model/ConfigKMS} kms
 */
ConfigConfig.prototype['kms'] = undefined;

/**
 * @member {module:model/ConfigLog} log
 */
ConfigConfig.prototype['log'] = undefined;

/**
 * @member {module:model/ConfigSentry} sentry
 */
ConfigConfig.prototype['sentry'] = undefined;

/**
 * @member {module:model/ConfigService} service
 */
ConfigConfig.prototype['service'] = undefined;

/**
 * @member {module:model/ConfigTLS} tls
 */
ConfigConfig.prototype['tls'] = undefined;

/**
 * @member {module:model/ConfigTTL} ttl
 */
ConfigConfig.prototype['ttl'] = undefined;






export default ConfigConfig;

