/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfigKMS model module.
 * @module model/ConfigKMS
 * @version 1.0
 */
class ConfigKMS {
    /**
     * Constructs a new <code>ConfigKMS</code>.
     * @alias module:model/ConfigKMS
     */
    constructor() { 
        
        ConfigKMS.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfigKMS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfigKMS} obj Optional instance to populate.
     * @return {module:model/ConfigKMS} The populated <code>ConfigKMS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfigKMS();

            if (data.hasOwnProperty('cache_enable')) {
                obj['cache_enable'] = ApiClient.convertToType(data['cache_enable'], 'Boolean');
            }
            if (data.hasOwnProperty('seed')) {
                obj['seed'] = ApiClient.convertToType(data['seed'], 'String');
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} cache_enable
 */
ConfigKMS.prototype['cache_enable'] = undefined;

/**
 * @member {String} seed
 */
ConfigKMS.prototype['seed'] = undefined;

/**
 * @member {String} uri
 */
ConfigKMS.prototype['uri'] = undefined;






export default ConfigKMS;

