/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsDetokenizedToken model module.
 * @module model/ModelsDetokenizedToken
 * @version 1.0
 */
class ModelsDetokenizedToken {
    /**
     * Constructs a new <code>ModelsDetokenizedToken</code>.
     * @alias module:model/ModelsDetokenizedToken
     */
    constructor() { 
        
        ModelsDetokenizedToken.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsDetokenizedToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsDetokenizedToken} obj Optional instance to populate.
     * @return {module:model/ModelsDetokenizedToken} The populated <code>ModelsDetokenizedToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsDetokenizedToken();

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], {'String': Object});
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} fields
 */
ModelsDetokenizedToken.prototype['fields'] = undefined;

/**
 * @member {String} token_id
 */
ModelsDetokenizedToken.prototype['token_id'] = undefined;






export default ModelsDetokenizedToken;

