/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsProductVersion model module.
 * @module model/ModelsProductVersion
 * @version 1.0
 */
class ModelsProductVersion {
    /**
     * Constructs a new <code>ModelsProductVersion</code>.
     * @alias module:model/ModelsProductVersion
     */
    constructor() { 
        
        ModelsProductVersion.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsProductVersion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsProductVersion} obj Optional instance to populate.
     * @return {module:model/ModelsProductVersion} The populated <code>ModelsProductVersion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsProductVersion();

            if (data.hasOwnProperty('db_schema_version')) {
                obj['db_schema_version'] = ApiClient.convertToType(data['db_schema_version'], 'Number');
            }
            if (data.hasOwnProperty('vault_id')) {
                obj['vault_id'] = ApiClient.convertToType(data['vault_id'], 'String');
            }
            if (data.hasOwnProperty('vault_version')) {
                obj['vault_version'] = ApiClient.convertToType(data['vault_version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} db_schema_version
 */
ModelsProductVersion.prototype['db_schema_version'] = undefined;

/**
 * @member {String} vault_id
 */
ModelsProductVersion.prototype['vault_id'] = undefined;

/**
 * The version of a Vault specified as a string consisting of version number, build number, and edition.
 * @member {String} vault_version
 */
ModelsProductVersion.prototype['vault_version'] = undefined;






export default ModelsProductVersion;

