/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsProperty model module.
 * @module model/ModelsProperty
 * @version 1.0
 */
class ModelsProperty {
    /**
     * Constructs a new <code>ModelsProperty</code>.
     * @alias module:model/ModelsProperty
     * @param isArray {Boolean} Whether the property is an array or a value.
     * @param name {String} The name of the property. This is the name of the column in the data_{collection_name} table. Must be unique.
     * @param piiTypeName {String} The name of the property type.
     */
    constructor(isArray, name, piiTypeName) { 
        
        ModelsProperty.initialize(this, isArray, name, piiTypeName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, isArray, name, piiTypeName) { 
        obj['is_array'] = isArray;
        obj['name'] = name;
        obj['pii_type_name'] = piiTypeName;
    }

    /**
     * Constructs a <code>ModelsProperty</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsProperty} obj Optional instance to populate.
     * @return {module:model/ModelsProperty} The populated <code>ModelsProperty</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsProperty();

            if (data.hasOwnProperty('creation_time')) {
                obj['creation_time'] = ApiClient.convertToType(data['creation_time'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('is_array')) {
                obj['is_array'] = ApiClient.convertToType(data['is_array'], 'Boolean');
            }
            if (data.hasOwnProperty('is_builtin')) {
                obj['is_builtin'] = ApiClient.convertToType(data['is_builtin'], 'Boolean');
            }
            if (data.hasOwnProperty('is_encrypted')) {
                obj['is_encrypted'] = ApiClient.convertToType(data['is_encrypted'], 'Boolean');
            }
            if (data.hasOwnProperty('is_index')) {
                obj['is_index'] = ApiClient.convertToType(data['is_index'], 'Boolean');
            }
            if (data.hasOwnProperty('is_nullable')) {
                obj['is_nullable'] = ApiClient.convertToType(data['is_nullable'], 'Boolean');
            }
            if (data.hasOwnProperty('is_readonly')) {
                obj['is_readonly'] = ApiClient.convertToType(data['is_readonly'], 'Boolean');
            }
            if (data.hasOwnProperty('is_unique')) {
                obj['is_unique'] = ApiClient.convertToType(data['is_unique'], 'Boolean');
            }
            if (data.hasOwnProperty('modification_time')) {
                obj['modification_time'] = ApiClient.convertToType(data['modification_time'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pii_type_name')) {
                obj['pii_type_name'] = ApiClient.convertToType(data['pii_type_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The time when the property was created in an RFC3339 format.
 * @member {Date} creation_time
 */
ModelsProperty.prototype['creation_time'] = undefined;

/**
 * The description of the property, If not provided, is set to an empty String.
 * @member {String} description
 */
ModelsProperty.prototype['description'] = undefined;

/**
 * Whether the property is an array or a value.
 * @member {Boolean} is_array
 */
ModelsProperty.prototype['is_array'] = undefined;

/**
 * Whether the property is created by Vault (or by the user)
 * @member {Boolean} is_builtin
 * @default false
 */
ModelsProperty.prototype['is_builtin'] = false;

/**
 * Whether the value is stored encrypted and decrypted when retrieved by a caller. Encryption provides extra protection against a malicious actor gaining access to the backend storage.
 * @member {Boolean} is_encrypted
 * @default false
 */
ModelsProperty.prototype['is_encrypted'] = false;

/**
 * Whether the backend storage is optimized for searches on this value.
 * @member {Boolean} is_index
 * @default false
 */
ModelsProperty.prototype['is_index'] = false;

/**
 * Whether the value of the field can be removed (set to null).
 * @member {Boolean} is_nullable
 * @default false
 */
ModelsProperty.prototype['is_nullable'] = false;

/**
 * When is_builtin is true, whether the user can modify values of this property.
 * @member {Boolean} is_readonly
 * @default false
 */
ModelsProperty.prototype['is_readonly'] = false;

/**
 * Whether the backend storage enforces unique values.
 * @member {Boolean} is_unique
 * @default false
 */
ModelsProperty.prototype['is_unique'] = false;

/**
 * The time when the property was last modified in an RFC3339 format.
 * @member {Date} modification_time
 */
ModelsProperty.prototype['modification_time'] = undefined;

/**
 * The name of the property. This is the name of the column in the data_{collection_name} table. Must be unique.
 * @member {String} name
 */
ModelsProperty.prototype['name'] = undefined;

/**
 * The name of the property type.
 * @member {String} pii_type_name
 */
ModelsProperty.prototype['pii_type_name'] = undefined;






export default ModelsProperty;

