/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsConfVar model module.
 * @module model/ModelsConfVar
 * @version 1.0
 */
class ModelsConfVar {
    /**
     * Constructs a new <code>ModelsConfVar</code>.
     * @alias module:model/ModelsConfVar
     */
    constructor() { 
        
        ModelsConfVar.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsConfVar</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsConfVar} obj Optional instance to populate.
     * @return {module:model/ModelsConfVar} The populated <code>ModelsConfVar</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsConfVar();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }


}

/**
 * The name of the configuration variable.
 * @member {String} name
 */
ModelsConfVar.prototype['name'] = undefined;

/**
 * The value of the configuration variable.
 * @member {Object} value
 */
ModelsConfVar.prototype['value'] = undefined;






export default ModelsConfVar;

