/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsQuery model module.
 * @module model/ModelsQuery
 * @version 1.0
 */
class ModelsQuery {
    /**
     * Constructs a new <code>ModelsQuery</code>.
     * @alias module:model/ModelsQuery
     */
    constructor() { 
        
        ModelsQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsQuery} obj Optional instance to populate.
     * @return {module:model/ModelsQuery} The populated <code>ModelsQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsQuery();

            if (data.hasOwnProperty('match')) {
                obj['match'] = ApiClient.convertToType(data['match'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, Object>} match
 */
ModelsQuery.prototype['match'] = undefined;






export default ModelsQuery;

