/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsTokenValue model module.
 * @module model/ModelsTokenValue
 * @version 1.0
 */
class ModelsTokenValue {
    /**
     * Constructs a new <code>ModelsTokenValue</code>.
     * @alias module:model/ModelsTokenValue
     * @param tokenId {String} The value of the token.
     */
    constructor(tokenId) { 
        
        ModelsTokenValue.initialize(this, tokenId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tokenId) { 
        obj['token_id'] = tokenId;
    }

    /**
     * Constructs a <code>ModelsTokenValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsTokenValue} obj Optional instance to populate.
     * @return {module:model/ModelsTokenValue} The populated <code>ModelsTokenValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsTokenValue();

            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The value of the token.
 * @member {String} token_id
 */
ModelsTokenValue.prototype['token_id'] = undefined;






export default ModelsTokenValue;

