/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsConfigurationDoc model module.
 * @module model/ModelsConfigurationDoc
 * @version 1.0
 */
class ModelsConfigurationDoc {
    /**
     * Constructs a new <code>ModelsConfigurationDoc</code>.
     * Additional information about the transformation, as key-value pairs.
     * @alias module:model/ModelsConfigurationDoc
     */
    constructor() { 
        
        ModelsConfigurationDoc.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsConfigurationDoc</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsConfigurationDoc} obj Optional instance to populate.
     * @return {module:model/ModelsConfigurationDoc} The populated <code>ModelsConfigurationDoc</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsConfigurationDoc();

            if (data.hasOwnProperty('non_masked_length')) {
                obj['non_masked_length'] = ApiClient.convertToType(data['non_masked_length'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Example transformation control key, in this case controlling the number of characters not masked in a data type.
 * @member {Number} non_masked_length
 */
ModelsConfigurationDoc.prototype['non_masked_length'] = undefined;






export default ModelsConfigurationDoc;

