/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsUpdateTokenRequest model module.
 * @module model/ModelsUpdateTokenRequest
 * @version 1.0
 */
class ModelsUpdateTokenRequest {
    /**
     * Constructs a new <code>ModelsUpdateTokenRequest</code>.
     * @alias module:model/ModelsUpdateTokenRequest
     */
    constructor() { 
        
        ModelsUpdateTokenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsUpdateTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsUpdateTokenRequest} obj Optional instance to populate.
     * @return {module:model/ModelsUpdateTokenRequest} The populated <code>ModelsUpdateTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsUpdateTokenRequest();

            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Replacement tags for the token.
 * @member {Array.<String>} tags
 */
ModelsUpdateTokenRequest.prototype['tags'] = undefined;






export default ModelsUpdateTokenRequest;

