/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsVaultGeneration model module.
 * @module model/ModelsVaultGeneration
 * @version 1.0
 */
class ModelsVaultGeneration {
    /**
     * Constructs a new <code>ModelsVaultGeneration</code>.
     * Vault Generation.
     * @alias module:model/ModelsVaultGeneration
     */
    constructor() { 
        
        ModelsVaultGeneration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsVaultGeneration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsVaultGeneration} obj Optional instance to populate.
     * @return {module:model/ModelsVaultGeneration} The populated <code>ModelsVaultGeneration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsVaultGeneration();

            if (data.hasOwnProperty('generation_number')) {
                obj['generation_number'] = ApiClient.convertToType(data['generation_number'], 'Number');
            }
            if (data.hasOwnProperty('modified_at')) {
                obj['modified_at'] = ApiClient.convertToType(data['modified_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Generation number.
 * @member {Number} generation_number
 */
ModelsVaultGeneration.prototype['generation_number'] = undefined;

/**
 * Modified at.
 * @member {Date} modified_at
 */
ModelsVaultGeneration.prototype['modified_at'] = undefined;






export default ModelsVaultGeneration;

