/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsLicense model module.
 * @module model/ModelsLicense
 * @version 1.0
 */
class ModelsLicense {
    /**
     * Constructs a new <code>ModelsLicense</code>.
     * @alias module:model/ModelsLicense
     */
    constructor() { 
        
        ModelsLicense.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsLicense</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsLicense} obj Optional instance to populate.
     * @return {module:model/ModelsLicense} The populated <code>ModelsLicense</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsLicense();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('expiration')) {
                obj['expiration'] = ApiClient.convertToType(data['expiration'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * The full license activation key.
 * @member {String} key
 */
ModelsLicense.prototype['key'] = undefined;

/**
 * The expiration date of the token in an RFC3339 format.
 * @member {Date} expiration
 */
ModelsLicense.prototype['expiration'] = undefined;






export default ModelsLicense;

