/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsRotatedToken model module.
 * @module model/ModelsRotatedToken
 * @version 1.0
 */
class ModelsRotatedToken {
    /**
     * Constructs a new <code>ModelsRotatedToken</code>.
     * @alias module:model/ModelsRotatedToken
     */
    constructor() { 
        
        ModelsRotatedToken.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsRotatedToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsRotatedToken} obj Optional instance to populate.
     * @return {module:model/ModelsRotatedToken} The populated <code>ModelsRotatedToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsRotatedToken();

            if (data.hasOwnProperty('new_token_id')) {
                obj['new_token_id'] = ApiClient.convertToType(data['new_token_id'], 'String');
            }
            if (data.hasOwnProperty('old_token_id')) {
                obj['old_token_id'] = ApiClient.convertToType(data['old_token_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} new_token_id
 */
ModelsRotatedToken.prototype['new_token_id'] = undefined;

/**
 * @member {String} old_token_id
 */
ModelsRotatedToken.prototype['old_token_id'] = undefined;






export default ModelsRotatedToken;

