/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsProperty from './ModelsProperty';

/**
 * The ModelsCollection model module.
 * @module model/ModelsCollection
 * @version 1.0
 */
class ModelsCollection {
    /**
     * Constructs a new <code>ModelsCollection</code>.
     * @alias module:model/ModelsCollection
     * @param name {String} The name of the collection.
     * @param type {module:model/ModelsCollection.TypeEnum} The schema prototype the collection is based on.
     */
    constructor(name, type) { 
        
        ModelsCollection.initialize(this, name, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type) { 
        obj['name'] = name;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ModelsCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsCollection} obj Optional instance to populate.
     * @return {module:model/ModelsCollection} The populated <code>ModelsCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsCollection();

            if (data.hasOwnProperty('creation_time')) {
                obj['creation_time'] = ApiClient.convertToType(data['creation_time'], 'Date');
            }
            if (data.hasOwnProperty('modification_time')) {
                obj['modification_time'] = ApiClient.convertToType(data['modification_time'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [ModelsProperty]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The time when the collection was created in an RFC3339 format.
 * @member {Date} creation_time
 */
ModelsCollection.prototype['creation_time'] = undefined;

/**
 * The time when the collection was last modified in an RFC3339 format.
 * @member {Date} modification_time
 */
ModelsCollection.prototype['modification_time'] = undefined;

/**
 * The name of the collection.
 * @member {String} name
 */
ModelsCollection.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/ModelsProperty>} properties
 */
ModelsCollection.prototype['properties'] = undefined;

/**
 * The schema prototype the collection is based on.
 * @member {module:model/ModelsCollection.TypeEnum} type
 */
ModelsCollection.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ModelsCollection['TypeEnum'] = {

    /**
     * value: "PERSONS"
     * @const
     */
    "PERSONS": "PERSONS",

    /**
     * value: "DATA"
     * @const
     */
    "DATA": "DATA"
};



export default ModelsCollection;

