/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsVaultGeneration from './ModelsVaultGeneration';
import ModelsWorker from './ModelsWorker';

/**
 * The ModelsAllGenerations model module.
 * @module model/ModelsAllGenerations
 * @version 1.0
 */
class ModelsAllGenerations {
    /**
     * Constructs a new <code>ModelsAllGenerations</code>.
     * @alias module:model/ModelsAllGenerations
     */
    constructor() { 
        
        ModelsAllGenerations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsAllGenerations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsAllGenerations} obj Optional instance to populate.
     * @return {module:model/ModelsAllGenerations} The populated <code>ModelsAllGenerations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsAllGenerations();

            if (data.hasOwnProperty('vault')) {
                obj['vault'] = ModelsVaultGeneration.constructFromObject(data['vault']);
            }
            if (data.hasOwnProperty('workers')) {
                obj['workers'] = ApiClient.convertToType(data['workers'], [ModelsWorker]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ModelsVaultGeneration} vault
 */
ModelsAllGenerations.prototype['vault'] = undefined;

/**
 * Workers generations.
 * @member {Array.<module:model/ModelsWorker>} workers
 */
ModelsAllGenerations.prototype['workers'] = undefined;






export default ModelsAllGenerations;

