/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModelsKMSStatus model module.
 * @module model/ModelsKMSStatus
 * @version 1.0
 */
class ModelsKMSStatus {
    /**
     * Constructs a new <code>ModelsKMSStatus</code>.
     * @alias module:model/ModelsKMSStatus
     */
    constructor() { 
        
        ModelsKMSStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsKMSStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsKMSStatus} obj Optional instance to populate.
     * @return {module:model/ModelsKMSStatus} The populated <code>ModelsKMSStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsKMSStatus();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The type of the configured KMS
 * @member {String} name
 */
ModelsKMSStatus.prototype['name'] = undefined;






export default ModelsKMSStatus;

