/**
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PiitypePIIType model module.
 * @module model/PiitypePIIType
 * @version 1.0
 */
class PiitypePIIType {
    /**
     * Constructs a new <code>PiitypePIIType</code>.
     * @alias module:model/PiitypePIIType
     */
    constructor() { 
        
        PiitypePIIType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PiitypePIIType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PiitypePIIType} obj Optional instance to populate.
     * @return {module:model/PiitypePIIType} The populated <code>PiitypePIIType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PiitypePIIType();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The description of the PII type.
 * @member {String} description
 */
PiitypePIIType.prototype['description'] = undefined;

/**
 * The name of the PII type.
 * @member {String} name
 */
PiitypePIIType.prototype['name'] = undefined;






export default PiitypePIIType;

